### ISSUE TITLE
lab8 sort

### ISSUE THREAD

**Issue by EM0T10NAl-DAMAGE** [segnoda/pwn-basic-challenge#2]
嘿 大大又是我 解了一個月還是想不出來
```
stack = array.pop(array.index(max(array, key=abs)))

libc = array.pop(array.index(max(array, key=abs))) - 0x21b97
```
我問題是這兩行 不懂用途
是leak libc的 base address 嗎？
如果是leak 那位甚要在 這裡leak 

而且我發現 它arr[10000] 程式其實給 10005個 
那多出來的5的 我也不知道裡面的值是從哪裡來的 是殘值 還是有意義的東西

我回去翻了lab7 但是沒得到太多有用的

感謝大大解答

**Comment by segnolin** [comment]
leak stack 其實在這題沒什麼作用，只是當時在解題的時候順便做的
至於 arr size 大小不一樣可能是為了對齊 stack 或者是有放 canary 和 rbp 或 ret address
我現在沒電腦所以沒辦法 debug，如果還有問題再問都 ok

**Comment by EM0T10NAl-DAMAGE** [comment]
又找了兩天 跟進去 qsort看了看 感覺就是information leak 但是還是沒啥收穫
希望大大直接點破 到今天這題也想了2個月 QQ 
偷偷許個願 希望錄個影 沒講解沒關西

**Comment by segnolin** [comment]
qsort 沒有問題
簡單來說就是在 sort 的時候，因為大小可以超過 array，所以可以 size 調大一點讓 canary 跟 libc 位置一起 sort 到想要的位置然後 leak 出來，最後在輸入 name 的時候把 canary 跟 one_gadget 擺好位置就拿到 shell
